src/main/java/com/amazingciel/blogspringapp/model/Message.java
package com.amazingciel.blogspringapp.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.format.annotation.DateTimeFormat;

import java.text.SimpleDateFormat;
import java.util.Date;

@Document(collection = "message")
public class Message {

    @Id
    private String id;
    private String owner;
    private String content;
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    private Date createDate;
    private String topicId;

    public String getId() {
        return id;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public String getFormatedDate(){
        return new SimpleDateFormat("dd MMM, yyyy").format(createDate);
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getTopicId() {
        return topicId;
    }

    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }
}

src/main/java/com/amazingciel/blogspringapp/model/Topic.java
package com.amazingciel.blogspringapp.model;


import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.format.annotation.DateTimeFormat;

import java.text.SimpleDateFormat;
import java.util.Date;

@Document(collection = "topic")
public class Topic {

    @Id
    private String id;
    private String title;
    private String content;
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    private Date createDate;
    private String imageName;

    public String getContent() {
        return content;
    }

    public void setContent(String Content) {
        content = Content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String Title) {
        title = Title;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public String getFormatedDate() {
        return new SimpleDateFormat("dd MMM, yyyy").format(createDate);
    }

    public void setCreateDate(Date CreateDate) {
        createDate = CreateDate;
    }

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String ImagePath) {
        imageName = ImagePath;
    }

    @Override
    public String toString() {
        return String.format("Topic { Title = %s, Content = %s, CreateDate = %s, ImagePath = %s }",
                title, content, createDate.toString(), imageName);
    }

    public String getId() {
        return id;
    }
}

src/main/java/com/amazingciel/blogspringapp/controller/MessageController.java
package com.amazingciel.blogspringapp.controller;

import com.amazingciel.blogspringapp.model.Message;
import com.amazingciel.blogspringapp.repository.MessageRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.Date;

@Controller
@RequestMapping(value = "/message")
public class MessageController {

    private final MessageRepository messageRepository;

    public MessageController(MessageRepository messageRepository) {
        this.messageRepository = messageRepository;
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public String Add(@Valid @ModelAttribute("newMessage") Message message, BindingResult result, ModelMap model){
        if (result.hasErrors()){
            return "error";
        }

        message.setCreateDate(new Date());

        messageRepository.Save(message);

        return String.format("redirect:/topic/%s", message.getTopicId());
    }
}

src/main/java/com/amazingciel/blogspringapp/controller/TopicController.java
package com.amazingciel.blogspringapp.controller;

import com.amazingciel.blogspringapp.model.Message;
import com.amazingciel.blogspringapp.model.Topic;
import com.amazingciel.blogspringapp.repository.MessageRepository;
import com.amazingciel.blogspringapp.repository.TopicRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import javax.validation.Valid;
import java.io.IOException;

@Controller
@RequestMapping(value = "/")
public class TopicController {

    private final TopicRepository topicRepository;
    private final MessageRepository messageRepository;

    public TopicController(TopicRepository topicRepository, MessageRepository messageRepository) {
        this.topicRepository = topicRepository;
        this.messageRepository = messageRepository;
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView All() {

        ModelAndView modelAndView = new ModelAndView("all-posts");

        modelAndView.addObject("topics", topicRepository.findAll());
        modelAndView.addObject("topicCount", topicRepository.Count());

        return modelAndView;
    }

    @RequestMapping(value = "/add", method = RequestMethod.GET)
    public ModelAndView Add() {
        return new ModelAndView("add", "topic", new Topic());
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public String Add(@Valid @ModelAttribute("topic") Topic topic,
                      @Valid @RequestParam("upload-image") MultipartFile file,
                      BindingResult result,
                      ModelMap model) throws IOException {
        if (result.hasErrors()) {
            return "error";
        }

        if (!file.isEmpty()){
            topicRepository.Save(topic, file);

        }
        else {
            topicRepository.Save(topic);
        }

        return "redirect:/success";
    }

    @RequestMapping(value = "/success", method = RequestMethod.GET)
    public String AddSucceed() {
        return "success";
    }

    @RequestMapping(value = "/topic/{id}")
    public ModelAndView Detail(@PathVariable("id") String id) {
        ModelAndView modelAndView = new ModelAndView("detail");

        Topic topic = topicRepository.findById(id);

        if (topic == null) {
            return new ModelAndView("error");
        }

        modelAndView.addObject("topic", topic);
        modelAndView.addObject("messages", messageRepository.getMessagesByTopicId(id));
        modelAndView.addObject("newMessage", new Message());

        return modelAndView;
    }
}

src/main/webapp/WEB-INF/pages/add.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<head>
    <title>UnitBean - Добавление статьи</title>
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>">
    <link rel='stylesheet' type="text/css" href=<c:url value="/resources/lib/bootstrap-4.0.0/dist/css/bootstrap.min.css"/> >
    <script src="<c:url value="/resources/lib/bootstrap-4.0.0/dist/js/bootstrap.min.js" />"></script>
</head>
<body>
    <div id="add-container">
        <form:form action="/add" method="POST" modelAttribute="topic" enctype="multipart/form-data">
            <form:hidden path="id" />
            <div id="form-header">Добавление статьи</div>
            <div class="form-group">
                <label for="title">Заголовок</label>
                <form:input id="title" path="title" cssClass="form-control" required="required" />
            </div>
            <div class="form-group">
                <label for="description">Описание</label>
                <form:textarea path="content" id="description" cols="30" rows="10" class="form-control" required="required" />
            </div>
            <div class="form-group">
                <div >Прикрепить изображение</div>
                <label for="file-upload" class="custom-file-upload">
                    <i class="fa fa-cloud-upload"></i>
                    <img src="<c:url value="/resources/img/cam.png"/>" alt="" class="btn btn-second">
                </label>
                <input name="upload-image" id="file-upload" type="file" accept="image/*"/>
                <input type="submit" value="Добавить" class="btn btn-bean float-right" />
                <a href="<c:url value="/"/>" class="btn btn-second float-right">Отмена</a>
            </div>
        </form:form>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/pages/all-posts.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>UnitBean - Все статьи</title>
    <link rel='stylesheet' type="text/css" href=<c:url value="/resources/lib/bootstrap-4.0.0/dist/css/bootstrap.min.css"/> >
    <script src="<c:url value="/resources/lib/bootstrap-4.0.0/dist/js/bootstrap.min.js" />"></script>
    <link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>">
</head>
<body>
    <div class="container" id="topic-container">
        <div id="header">
            <div id="black-logo">
                <img src="<c:url value="/resources/img/black-logo.png"/>" alt=""/>
            </div>
            <a href="<c:url value="/add"/>" class="text-bean full-rounded" id="add-button">Добавить статью</a>
            <div id="header-text">Статьи, ${topicCount}</div>
        </div>
        <div id="topics">
            <c:forEach var="topic" items="${topics}">
                <div class="card topic top-left-rounded">
                    <a href="/topic/${topic.id}" class="card-header">
                        <img class="top-left-rounded" src="<c:url value="/resources/img/topic-image/${topic.imageName}"/>" alt="">
                    </a>
                    <div class="card-body">
                        <div class="topic-title text-bold">
                            ${topic.title}
                        </div>
                        ${topic.formatedDate}
                    </div>
                    <div class="card-footer">
                            ${topic.content}
                    </div>
                </div>
            </c:forEach>
        </div>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/pages/detail.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>UnitBean - ${topic.title}</title>
    <link rel='stylesheet' type="text/css" href="<c:url value="/resources/lib/bootstrap-4.0.0/dist/css/bootstrap.min.css"/>" />
    <script src="<c:url value="/resources/lib/bootstrap-4.0.0/dist/js/bootstrap.min.js"/>"></script>
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>" />
</head>
<body>
    <div id="detail-container" class="container">
        <div class="card border-0">
            <div class="card-header border-0">
                <div class="card-title" id="detail-title">${topic.title}</div>
                <img src="<c:url value="/resources/img/topic-image/${topic.imageName}"/>" class="detail-image" alt="">
            </div>
            <div class="card-body">
                ${topic.content}
            </div>
            <div class="card-footer border-0">
                <form:form method="POST" action="/message/add" modelAttribute="newMessage">
                    <form:hidden path="id" />
                    <form:hidden path="topicId" value="${topic.id}" />
                    <div class="message-input-width">
                        <div class="container-sm msg-icon ">
                            <img src="<c:url value="/resources/img/message-owner.svg"/>" alt="Owner Icon">
                        </div>
                    </div>
                    <div class="input-group container-sm" id="message-field-group">
                        <form:input path="owner" type="text" cssClass="form-control" placeholder="Имя пользователя" />
                        <form:input path="content" type="text" cssClass="form-control" placeholder="Ваш коментарий" />
                    </div>
                    <div class="message-input-width">
                        <input type="submit" class="btn btn-bean container-sm" value=">" id="message-submit">
                    </div>
                </form:form>
                <c:forEach var="msg" items="${messages}" >
                    <div class="message">
                        <div>
                            <div class="container-sm msg-icon">
                                <img src="<c:url value="/resources/img/message-owner.svg"/>" alt="Owner Icon">
                            </div>
                        </div>
                        <div>
                            <div>
                                <div class="text-bold">${msg.owner}</div>
                                <div class="message-date">${msg.formatedDate}</div>
                            </div>
                            <div>${msg.content}</div>
                        </div>
                    </div>
                </c:forEach>
            </div>
        </div>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/pages/success.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<head>
    <title>UnitBean - статья добавлена</title>
    <link rel='stylesheet' type="text/css" href=<c:url value="/resources/lib/bootstrap-4.0.0/dist/css/bootstrap.min.css"/> >
    <script src="<c:url value="/resources/lib/bootstrap-4.0.0/dist/js/bootstrap.min.js" />"></script>
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>">
</head>
<body>
    <div class="container">
        <img id="logo-success" src="<c:url value="/resources/img/bean.png" />" alt="UnitBean logo">
        <div class="text-bean" id="text-success">Поздравляем Вас с успешным добавлением статьи в блог UnitBean!</div>
    </div>
</body>
</html>